CREATE TABLE PEOPLE(
PEOPLE_ID VARCHAR(255)PRIMARY KEY,
FIRST_NAME VARCHAR (255),
LAST_NAME VARCHAR (255),
PASSPORT_ID VARCHAR (255)
)CHARACTER SET utf8mb4;
INSERT INTO PEOPLE (PEOPLE_ID,FIRST_NAME,LAST_NAME,PASSPORT_ID) 
VALUES ('1','Олексій','Марченко',4837291);
INSERT INTO PEOPLE (PEOPLE_ID,FIRST_NAME,LAST_NAME,PASSPORT_ID) 
VALUES ('2','Іван','Ковальчук',1029384);
INSERT INTO PEOPLE (PEOPLE_ID,FIRST_NAME,LAST_NAME,PASSPORT_ID) 
VALUES ('3','Марія','Ткаченко',5647382);
INSERT INTO PEOPLE (PEOPLE_ID,FIRST_NAME,LAST_NAME,PASSPORT_ID) 
VALUES ('4','Наталаія','Гриценко',8273645);
INSERT INTO PEOPLE (PEOPLE_ID,FIRST_NAME,LAST_NAME,PASSPORT_ID) 
VALUES ('5','Андрій','Бондаренко',4837291);

CREATE TABLE PHONE_BOOK(
PEOPLE_PHONE_ID VARCHAR(255),
PEOPLE_ID INT(2)PRIMARY KEY,
PHONE_NUMBER VARCHAR (255),
EMAIL_TEXT VARCHAR (255)
);
INSERT INTO PHONE_BOOK (PEOPLE_PHONE_ID,PEOPLE_ID,PHONE_NUMBER,EMAIL_TEXT)
VALUES (1,1,'+380961903185','sannsa777@gmail.com');
INSERT INTO PHONE_BOOK (PEOPLE_PHONE_ID,PEOPLE_ID,PHONE_NUMBER,EMAIL_TEXT)
VALUES (2,2,'+380932345678','ivankovalchuk@gmail.com');
INSERT INTO PHONE_BOOK (PEOPLE_PHONE_ID,PEOPLE_ID,PHONE_NUMBER,EMAIL_TEXT)
VALUES (3,3,'+3800503456789','mariatkachenko@gmail.com');
INSERT INTO PHONE_BOOK (PEOPLE_PHONE_ID,PEOPLE_ID,PHONE_NUMBER,EMAIL_TEXT)
VALUES (4,4,'+380664567890','nataliagritsenko@gmail.com');
INSERT INTO PHONE_BOOK (PEOPLE_PHONE_ID,PEOPLE_ID,PHONE_NUMBER,EMAIL_TEXT)
VALUES (5,5,'+3809575678901','andriybondarenko@gmail.com');
SELECT * FROM PEOPLE ORDER BY LAST_NAME;
SELECT PHONE_NUMBER , EMAIL_TEXT FROM PHONE_BOOK pb;
SELECT * FROM PEOPLE WHERE FIRST_NAME = 'Олексій' AND LAST_NAME = 'Марченко';
SELECT * FROM PEOPLE WHERE FIRST_NAME = 'Іван' OR FIRST_NAME = 'Марія';
SELECT * FROM PEOPLE WHERE NOT FIRST_NAME = 'Іван';
SELECT * FROM PEOPLE WHERE FIRST_NAME='Марія'AND LAST_NAME='Ткаченко';
SELECT * FROM PEOPLE WHERE PASSPORT_ID=4837291 OR PASSPORT_ID=1029384;
SELECT * FROM PEOPLE WHERE NOT FIRST_NAME='Наталія';
UPDATE PEOPLE SET FIRST_NAME ='Наталія' WHERE PEOPLE_ID=4;
SELECT * FROM PEOPLE where people_id=4;
SELECT * FROM PEOPLE WHERE LAST_NAME LIKE '%енко';
SELECT * FROM PEOPLE WHERE FIRST_NAME LIKE'%а%';
SELECT * FROM PEOPLE LIMIT 2;
SELECT * FROM PEOPLE 




























































































































































































CREATE TABLE Persons (
                         PersonID int UNIQUE AUTO_INCREMENT NOT NULL,
                         LastName varchar(255) NOT NULL,
                         FirstName varchar(255) NOT NULL,
                         Gender varchar(80) NOT NULL,
                         Title varchar(255) NOT NULL,
                         Nat varchar(255) NOT NULL
);
iNSERT INTO Persons (LastName,FirstName,Gender,Title,Nat) 
VALUES ('John','Doe','male','Mr','US');
select * from Persons p 





































CREATE TABLE PERSONS(
PERSONS_ID INT PRIMARY KEY,
FIRST_NAME VARCHAR(30),
LAST_NAME VARCHAR(30),
AGE INT(3),
EMAIL VARCHAR(255) 
);
INSERT INTO PERSONS (PERSONS_ID,FIRST_NAME,LAST_NAME,AGE,EMAIL)
VALUES (1,'PETRO','KISILOV',57,'petrogram@gmail.com');
INSERT INTO PERSONS(PERSONS_ID,FIRST_NAME,LAST_NAME,AGE,EMAIL)
VALUES (2,'VASILIY','LIPUTIN',34,NULL);
INSERT INTO PERSONS(PERSONS_ID,FIRST_NAME,LAST_NAME,AGE,EMAIL)
VALUES (3,'TATYANA','MATUSHKOVA',28,NULL);
INSERT INTO PERSONS (PERSONS_ID,FIRST_NAME,LAST_NAME,AGE,EMAIL)
VALUES (4,'Zuzanna','Nowak',21,NULL);
INSERT INTO PERSONS (PERSONS_ID,FIRST_NAME,LAST_NAME,AGE,EMAIL)
VALUES (5,'Muhammad','Falasi',76,NULL);
INSERT INTO PERSONS (PERSONS_ID,FIRST_NAME,LAST_NAME,AGE,EMAIL)
VALUES (6,'Leonardo','Rossi',23,NULL);
INSERT INTO PERSONS (PERSONS_ID,FIRST_NAME,LAST_NAME,AGE,EMAIL)
VALUES(7,'Ben','Shcmidt',54,'bentd@gmail.com');
INSERT INTO PERSONS (PERSONS_ID,FIRST_NAME,LAST_NAME,AGE,EMAIL)
VALUES (8,'Sofia','Bianchi',19,'sofiagrace@gmail.com');
CREATE TABLE ADDRESS(
ADDRESS_ID INT,
PERSONS_ID INT,
ZIP_CODE VARCHAR(6),
STREET_NAME VARCHAR(255),
CITY_NAME VARCHAR(255),
HOUSE_NUMBER VARCHAR(255)
);
INSERT INTO ADDRESS (ADDRESS_ID,PERSONS_ID,ZIP_CODE,STREET_NAME,CITY_NAME,HOUSE_NUMBER)
VALUES (1,1,'790','Brunchansky','Dubai','86');
INSERT INTO ADDRESS 
VALUES (2,2,'810','STUPIKOVA','Paris','75');
INSERT INTO ADDRESS
VALUES (3,3,'920','Rabinka','Brazil','45');
INSERT INTO ADDRESS 
VALUES (4,4,'1020','Poland','Warsaw','78');
INSERT INTO ADDRESS 
VALUES (5,5,'2020','Spain','Madrid','74');
INSERT INTO ADDRESS 
VALUES (6,6,'2341','Italy','Rome','73');
INSERT INTO ADDRESS 
VALUES (7,7,'1020','Germany','Berlin','34');
INSERT INTO ADDRESS 
VALUES (8,8,'2341','Italy','Rome','90');
SELECT * FROM PERSONS p;
SELECT FIRST_NAME,CITY_NAME FROM PERSONS p INNER JOIN ADDRESS ON p.PERSONS_ID=ADDRESS.PERSONS_ID;
SELECT HOUSE_NUMBER,COUNT(*) FROM ADDRESS GROUP BY HOUSE_NUMBER;
